name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What did you do?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
  - type: input
    id: version
    attributes:
      label: Version / OS
